builds:
  - binary: convertdate
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  # If set to auto, will mark the release as not ready for production
  prerelease : auto

universal_binaries:
  # If left as false, your end release might have both several macOS archives:
  # amd64, arm64 and all. For Mac M1 use true.
  - replace: true

brews:
  -
    name: convertdate
    homepage: https://github.com/Ulleri-Tech/nepali-date-cli
    tap:
      owner: Ulleri-Tech
      name: homebrew-tap-ulleritech
    commit_author:
      name: thebinij
      email: hello@bnijshrestha.com.np
       
    description: "Software to convert AD and BS dates"

    # SPDX identifier of your app's license.
    license: "MIT"

    install: |
      bin.install "convertdate"

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"





